### ISSUE TITLE
Says Its A Virus

### ISSUE THREAD

**Issue by Jrmcwicked** [AlizerUncaged/GDM-Windows#10]
I Know Its Not A Virus Since My Friends Have It So What Do I Do

**Comment by thunderfurry** [comment]
For me its either a network error, or its "forbidden"

**Comment by SagMeinenNamen** [comment]
> I Know Its Not A Virus Since My Friends Have It So What Do I Do

Hey, I just wanted to inform you that it still can be a virus even when your friends have it, it could (probably is, at least in my opinion) spyware or something similar. Your friends will not notice what the Programm is executing in the background, alizer already told me that it gets detected as a virus because it is injection files into the original gd. I'm not too sure about that statement since they are many programs that do this and are marked as safe. I decided to not trust this and don't install it, however what you do is your decision, thanks for your time :)

**Comment by AlizerUncaged** [comment]
bro the source code is right here lol just because you cant code you can use it as an excuse

**Comment by SagMeinenNamen** [comment]
Hi Alizer, I checked the code, it seems safe, but the code and the zip do dot have to be from the exact same origin, you should know that, because there are many factors that indicate that it the end result is not the complied code. I will let you find out these yourself

**Comment by CodyMarkix** [comment]
> the end result is not the compiled code.

this is why you compile Github programs yourself (partially satire)

**Comment by SagMeinenNamen** [comment]
I see your point, but this would be only a option for people who want to invest time for this (and of course known how to compile). Most people who download this, have no other choice than to hope, it's not some kind of malware, which is no go

**Comment by CodyMarkix** [comment]
> I see your point, but this would be only a option for people who want to invest time for this (and of course known how to compile). Most people who download this, have no other choice than to hope, it's not some kind of malware, which is no go

I agree, not everyone isn't afraid of the "h4xx0ry" commabd line, but I also believe, it's the repo maintainer's job to walk people - newbie or experienced - through compiling their software in a clear, well instructed way so that anyone and their dog can do it.

**Comment by YoCatt** [comment]
the code is safe, windows just thinks it's a malware because it injects app extensions to apps like in this case, GDM injects a DLL to Geometry Dash so everything functions correctly.
Example: You join to a level session and you can see the players there. That's what GDM.dll does.
If you have any issues, disable your antivirus or make an exclusion to it thru your antivirus software.

**Comment by SagMeinenNamen** [comment]
@YoCatt please read my first comment.
